version: '2'

volumes:
  mqtt-data:
  mqtt-log:

services:
  mqtt:
    build: ./mqtt
    container_name: mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - "mqtt-data:/mqtt/data"
      - "mqtt-log:/mqtt/log"